import { describe, it, expect } from "vitest";
import { exportDiagramToSQL } from "@/lib/sql-export";
import type { Diagram } from "@/lib/domain";

const testDiagram: Diagram = {
  id: "d1",
  name: "Test",
  databaseType: "postgresql",
  tables: [
    {
      id: "t1",
      name: "users",
      fields: [
        { id: "f1", name: "id", type: "SERIAL", primaryKey: true, unique: false, nullable: false, isForeignKey: false },
        { id: "f2", name: "email", type: "VARCHAR(255)", primaryKey: false, unique: true, nullable: false, isForeignKey: false },
        { id: "f3", name: "name", type: "TEXT", primaryKey: false, unique: false, nullable: true, isForeignKey: false },
      ],
      indexes: [],
      x: 0,
      y: 0,
      isView: false,
    },
    {
      id: "t2",
      name: "orders",
      fields: [
        { id: "f4", name: "id", type: "SERIAL", primaryKey: true, unique: false, nullable: false, isForeignKey: false },
        {
          id: "f5",
          name: "user_id",
          type: "INTEGER",
          primaryKey: false,
          unique: false,
          nullable: false,
          isForeignKey: true,
          references: { table: "users", field: "id" },
        },
      ],
      indexes: [],
      x: 0,
      y: 0,
      isView: false,
    },
  ],
  relationships: [],
  createdAt: "2024-01-01T00:00:00.000Z",
};

describe("exportDiagramToSQL", () => {
  it("exports PostgreSQL CREATE TABLE statements", () => {
    const sql = exportDiagramToSQL(testDiagram);
    expect(sql).toContain('CREATE TABLE "users"');
    expect(sql).toContain('"email"');
    expect(sql).toContain("NOT NULL");
    expect(sql).toContain("UNIQUE");
    expect(sql).toContain("PRIMARY KEY");
  });

  it("exports foreign key constraints", () => {
    const sql = exportDiagramToSQL(testDiagram);
    expect(sql).toContain("FOREIGN KEY");
    expect(sql).toContain("REFERENCES");
  });

  it("exports to MySQL dialect", () => {
    const sql = exportDiagramToSQL(testDiagram, "mysql");
    expect(sql).toContain("`users`");
    expect(sql).toContain("`email`");
    expect(sql).toContain("INT AUTO_INCREMENT");
  });

  it("includes header comment", () => {
    const sql = exportDiagramToSQL(testDiagram);
    expect(sql).toContain("Generated by db-schema-viewer");
  });
});
