import type { Diagram } from "@/lib/domain";

/**
 * Export a Diagram to PlantUML entity-relationship format.
 */
export function exportDiagramToPlantUML(diagram: Diagram): string {
  const lines: string[] = [];

  lines.push("@startuml");
  lines.push("' Generated by db-schema-viewer");
  lines.push("skinparam linetype ortho");
  lines.push("");

  for (const table of diagram.tables) {
    const keyword = table.isView ? "class" : "entity";
    const stereotype = table.isView ? " <<View>>" : "";
    const safeName = safePUML(table.name);

    lines.push(`${keyword} "${table.name}" as ${safeName}${stereotype} {`);

    // Primary keys go in the first compartment
    const pkFields = table.fields.filter((f) => f.primaryKey);
    const otherFields = table.fields.filter((f) => !f.primaryKey);

    for (const field of pkFields) {
      const modifiers = buildModifiers(field);
      lines.push(`  * ${field.name} : ${field.type}${modifiers}`);
    }

    if (pkFields.length > 0 && otherFields.length > 0) {
      lines.push("  --");
    }

    for (const field of otherFields) {
      const prefix = field.nullable ? "  " : "  * ";
      const modifiers = buildModifiers(field);
      lines.push(`${prefix}${field.name} : ${field.type}${modifiers}`);
    }

    lines.push("}");
    lines.push("");
  }

  // Relationships
  for (const rel of diagram.relationships) {
    const srcTable = diagram.tables.find((t) => t.id === rel.sourceTableId);
    const tgtTable = diagram.tables.find((t) => t.id === rel.targetTableId);
    if (!srcTable || !tgtTable) continue;

    const srcName = safePUML(srcTable.name);
    const tgtName = safePUML(tgtTable.name);

    const srcField = srcTable.fields.find((f) => f.id === rel.sourceFieldId);
    const tgtField = tgtTable.fields.find((f) => f.id === rel.targetFieldId);
    const label = srcField && tgtField
      ? ` : ${srcField.name}`
      : "";

    let arrow: string;
    switch (rel.cardinality) {
      case "one-to-one":
        arrow = "||--||";
        break;
      case "one-to-many":
        arrow = "}o--||";
        break;
      case "many-to-many":
        arrow = "}o--o{";
        break;
      default:
        arrow = "}o--||";
    }

    // Parent (target/PK side) on left, child (source/FK side) on right
    lines.push(`${tgtName} ${arrow} ${srcName}${label}`);
  }

  lines.push("");
  lines.push("@enduml");

  return lines.join("\n");
}

function safePUML(name: string): string {
  return name.replace(/[^a-zA-Z0-9_]/g, "_");
}

function buildModifiers(field: {
  primaryKey: boolean;
  unique: boolean;
  isForeignKey: boolean;
  nullable: boolean;
}): string {
  const tags: string[] = [];
  if (field.primaryKey) tags.push("PK");
  if (field.isForeignKey) tags.push("FK");
  if (field.unique && !field.primaryKey) tags.push("UK");
  return tags.length > 0 ? ` <<${tags.join(", ")}>>` : "";
}
