import type { Diagram, DBTable, DBField, DatabaseType } from "@/lib/domain";

const TYPE_MAP: Record<string, Partial<Record<DatabaseType, string>>> = {
  serial: { mysql: "INT AUTO_INCREMENT", sqlite: "INTEGER", bigquery: "INT64" },
  bigserial: { mysql: "BIGINT AUTO_INCREMENT", sqlite: "INTEGER", bigquery: "INT64" },
  boolean: { mysql: "TINYINT(1)", bigquery: "BOOL" },
  jsonb: { mysql: "JSON", sqlite: "TEXT", bigquery: "STRING" },
  json: { sqlite: "TEXT", bigquery: "STRING" },
  uuid: { mysql: "CHAR(36)", sqlite: "TEXT", bigquery: "STRING" },
  timestamptz: { mysql: "TIMESTAMP", sqlite: "TEXT", bigquery: "TIMESTAMP" },
  text: { bigquery: "STRING" },
  varchar: { bigquery: "STRING" },
  integer: { bigquery: "INT64" },
  bigint: { bigquery: "INT64" },
  smallint: { bigquery: "INT64" },
  real: { bigquery: "FLOAT64" },
  "double precision": { bigquery: "FLOAT64" },
  numeric: { bigquery: "NUMERIC" },
  bytea: { mysql: "BLOB", sqlite: "BLOB", bigquery: "BYTES" },
};

function mapType(type: string, targetDb: DatabaseType): string {
  const lower = type.toLowerCase().replace(/\(.*\)/, "").trim();
  const mapped = TYPE_MAP[lower];
  if (mapped?.[targetDb]) {
    return mapped[targetDb]!;
  }
  return type;
}

function quoteIdentifier(name: string, dbType: DatabaseType): string {
  switch (dbType) {
    case "mysql":
    case "mariadb":
    case "clickhouse":
      return `\`${name}\``;
    case "postgresql":
    case "supabase":
    case "cockroachdb":
      return `"${name}"`;
    case "sqlite":
      return `"${name}"`;
    case "bigquery":
    case "snowflake":
      return name;
    default:
      return `"${name}"`;
  }
}

function generateCreateTable(table: DBTable, targetDb: DatabaseType): string {
  const qName = table.schema
    ? `${quoteIdentifier(table.schema, targetDb)}.${quoteIdentifier(table.name, targetDb)}`
    : quoteIdentifier(table.name, targetDb);

  const lines: string[] = [];
  lines.push(`CREATE TABLE ${qName} (`);

  const fieldDefs: string[] = [];
  const pks: string[] = [];

  for (const field of table.fields) {
    const parts: string[] = [];
    parts.push(`  ${quoteIdentifier(field.name, targetDb)}`);
    parts.push(mapType(field.type, targetDb));

    if (field.primaryKey) pks.push(field.name);
    if (!field.nullable) parts.push("NOT NULL");
    if (field.unique && !field.primaryKey) parts.push("UNIQUE");
    if (field.default) parts.push(`DEFAULT ${field.default}`);

    fieldDefs.push(parts.join(" "));
  }

  if (pks.length > 0) {
    fieldDefs.push(
      `  PRIMARY KEY (${pks.map((pk) => quoteIdentifier(pk, targetDb)).join(", ")})`
    );
  }

  lines.push(fieldDefs.join(",\n"));
  lines.push(");");

  return lines.join("\n");
}

function generateFK(
  table: DBTable,
  field: DBField,
  targetDb: DatabaseType
): string | null {
  if (!field.references) return null;
  const srcTable = quoteIdentifier(table.name, targetDb);
  const srcCol = quoteIdentifier(field.name, targetDb);
  const refTable = quoteIdentifier(field.references.table, targetDb);
  const refCol = quoteIdentifier(field.references.field, targetDb);

  return `ALTER TABLE ${srcTable} ADD CONSTRAINT fk_${table.name}_${field.name} FOREIGN KEY (${srcCol}) REFERENCES ${refTable} (${refCol});`;
}

export function exportDiagramToSQL(diagram: Diagram, targetDb?: DatabaseType): string {
  const db = targetDb ?? diagram.databaseType;
  const parts: string[] = [];

  parts.push(`-- Generated by db-schema-viewer`);
  parts.push(`-- Database: ${db}`);
  parts.push(`-- Date: ${new Date().toISOString()}`);
  parts.push("");

  // Create tables
  for (const table of diagram.tables) {
    if (table.isView) continue;
    parts.push(generateCreateTable(table, db));
    parts.push("");
  }

  // Foreign keys
  for (const table of diagram.tables) {
    for (const field of table.fields) {
      const fk = generateFK(table, field, db);
      if (fk) parts.push(fk);
    }
  }

  return parts.join("\n");
}
