import { describe, it, expect } from "vitest";
import { exportDiagramToSQL } from "../../src/sql-export";
import type { Diagram } from "../../src/domain";

const testDiagram: Diagram = {
  id: "d1",
  name: "Test",
  databaseType: "postgresql",
  tables: [
    {
      id: "t1",
      name: "users",
      fields: [
        { id: "f1", name: "id", type: "SERIAL", primaryKey: true, unique: false, nullable: false, isForeignKey: false },
        { id: "f2", name: "email", type: "VARCHAR(255)", primaryKey: false, unique: true, nullable: false, isForeignKey: false },
        { id: "f3", name: "name", type: "TEXT", primaryKey: false, unique: false, nullable: true, isForeignKey: false },
      ],
      indexes: [],
      x: 0,
      y: 0,
      isView: false,
    },
    {
      id: "t2",
      name: "orders",
      fields: [
        { id: "f4", name: "id", type: "SERIAL", primaryKey: true, unique: false, nullable: false, isForeignKey: false },
        {
          id: "f5",
          name: "user_id",
          type: "INTEGER",
          primaryKey: false,
          unique: false,
          nullable: false,
          isForeignKey: true,
          references: { table: "users", field: "id" },
        },
      ],
      indexes: [],
      x: 0,
      y: 0,
      isView: false,
    },
  ],
  relationships: [],
  createdAt: "2024-01-01T00:00:00.000Z",
};

describe("exportDiagramToSQL", () => {
  it("exports PostgreSQL CREATE TABLE statements", () => {
    const sql = exportDiagramToSQL(testDiagram);
    expect(sql).toContain('CREATE TABLE "users"');
    expect(sql).toContain('"email"');
    expect(sql).toContain("NOT NULL");
    expect(sql).toContain("UNIQUE");
    expect(sql).toContain("PRIMARY KEY");
  });

  it("exports foreign key constraints", () => {
    const sql = exportDiagramToSQL(testDiagram);
    expect(sql).toContain("FOREIGN KEY");
    expect(sql).toContain("REFERENCES");
  });

  it("exports to MySQL dialect", () => {
    const sql = exportDiagramToSQL(testDiagram, "mysql");
    expect(sql).toContain("`users`");
    expect(sql).toContain("`email`");
    expect(sql).toContain("INT AUTO_INCREMENT");
  });

  it("includes header comment", () => {
    const sql = exportDiagramToSQL(testDiagram);
    expect(sql).toContain("Generated by db-schema-viewer");
  });

  it("exports ON DELETE CASCADE ON UPDATE CASCADE for FKs", () => {
    const sql = exportDiagramToSQL(testDiagram);
    expect(sql).toContain("ON DELETE CASCADE ON UPDATE CASCADE");
  });

  it("skips CASCADE for BigQuery", () => {
    const sql = exportDiagramToSQL(testDiagram, "bigquery");
    expect(sql).not.toContain("ON DELETE CASCADE");
  });

  it("exports CREATE INDEX for tables with indexes", () => {
    const diagram: Diagram = {
      ...testDiagram,
      tables: [
        {
          ...testDiagram.tables[0]!,
          indexes: [
            { id: "idx1", name: "idx_users_email", columns: ["email"], unique: true },
            { id: "idx2", name: "idx_users_name", columns: ["name"], unique: false },
          ],
        },
        testDiagram.tables[1]!,
      ],
    };
    const sql = exportDiagramToSQL(diagram);
    expect(sql).toContain("CREATE UNIQUE INDEX");
    expect(sql).toContain("idx_users_email");
    expect(sql).toContain("CREATE INDEX");
    expect(sql).toContain("idx_users_name");
  });

  it("exports COMMENT ON for PostgreSQL tables with comments", () => {
    const diagram: Diagram = {
      ...testDiagram,
      tables: [
        {
          ...testDiagram.tables[0]!,
          comment: "Main users table",
          fields: [
            { ...testDiagram.tables[0]!.fields[0]!, comment: "Auto-increment PK" },
            ...testDiagram.tables[0]!.fields.slice(1),
          ],
        },
        testDiagram.tables[1]!,
      ],
    };
    const sql = exportDiagramToSQL(diagram, "postgresql");
    expect(sql).toContain("COMMENT ON TABLE");
    expect(sql).toContain("Main users table");
    expect(sql).toContain("COMMENT ON COLUMN");
    expect(sql).toContain("Auto-increment PK");
  });

  it("skips COMMENT ON for MySQL", () => {
    const diagram: Diagram = {
      ...testDiagram,
      tables: [
        { ...testDiagram.tables[0]!, comment: "Should not appear" },
        testDiagram.tables[1]!,
      ],
    };
    const sql = exportDiagramToSQL(diagram, "mysql");
    expect(sql).not.toContain("COMMENT ON");
  });

  it("exports CREATE TYPE for ENUM fields (PostgreSQL)", () => {
    const diagram: Diagram = {
      ...testDiagram,
      tables: [
        {
          ...testDiagram.tables[0]!,
          fields: [
            ...testDiagram.tables[0]!.fields,
            { id: "f10", name: "role", type: "ENUM(Role)", primaryKey: false, unique: false, nullable: true, isForeignKey: false },
          ],
        },
        testDiagram.tables[1]!,
      ],
    };
    const sql = exportDiagramToSQL(diagram, "postgresql");
    expect(sql).toContain("CREATE TYPE");
    expect(sql).toContain("Role");
  });

  it("exports CREATE VIEW for view tables", () => {
    const diagram: Diagram = {
      ...testDiagram,
      tables: [
        ...testDiagram.tables,
        {
          id: "v1",
          name: "active_users",
          fields: [
            { id: "vf1", name: "id", type: "INTEGER", primaryKey: false, unique: false, nullable: true, isForeignKey: false },
            { id: "vf2", name: "email", type: "VARCHAR", primaryKey: false, unique: false, nullable: true, isForeignKey: false },
          ],
          indexes: [],
          x: 0,
          y: 0,
          isView: true,
        },
      ],
    };
    const sql = exportDiagramToSQL(diagram);
    expect(sql).toContain("CREATE OR REPLACE VIEW");
    expect(sql).toContain("active_users");
  });
});
